// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zVsTStIu_OJBV9Xc1SfWsMjsn5iPLO4',
    appId: '1:740372447253:web:2f4cbe9f319d0d84ee0e1c',
    messagingSenderId: '740372447253',
    projectId: 'lineapii',
    authDomain: 'lineapii.firebaseapp.com',
    storageBucket: 'lineapii.appspot.com',
    measurementId: 'G-6K1XZNVFWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDejz1R9rDHZ2p21DosNyE5WORazS0dp3M',
    appId: '1:740372447253:android:1ddd7dfef580fcd8ee0e1c',
    messagingSenderId: '740372447253',
    projectId: 'lineapii',
    storageBucket: 'lineapii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLtFbRn1sA-1tvJGKv4Gjfl74t8aucibc',
    appId: '1:740372447253:ios:04b410bf5787f692ee0e1c',
    messagingSenderId: '740372447253',
    projectId: 'lineapii',
    storageBucket: 'lineapii.appspot.com',
    iosClientId: '740372447253-too1gqhf5m17vpgjk3tlfig0oh9mfuu9.apps.googleusercontent.com',
    iosBundleId: 'co.ucundinamarca.project0',
  );
}
